
import gnu.io.CommPortIdentifier;
import gnu.io.PortInUseException;
import gnu.io.SerialPort;
import gnu.io.UnsupportedCommOperationException;
import static java.awt.image.ImageObserver.ERROR;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pasxzy72
 */
public final class HouseForm extends javax.swing.JFrame {

   private final String room1_off ="0";
   private final String room1_on ="1";
   
   private final String all_off ="3";
   private final String all_on ="2";
   
   private final String room3_off ="4";
   private final String room3_on ="5";
   
   
  
   private final String door_close ="6";
   private final String door_open ="7";
   
   private final String fan_off ="9";
   private final String fan_on ="8";
   
   
   private OutputStream output = null;
  
   SerialPort serialPort;
   
   private final String port = "COM25";
   private final int timeOut = 2000000000; 
   private final int dataRate = 115200;
   
    public HouseForm() {
        
        initComponents();
        connexion();
    }
    
 public void connexion(){
    CommPortIdentifier portId = null;
    Enumeration portEnum = CommPortIdentifier.getPortIdentifiers();
    while(portEnum.hasMoreElements()){
    CommPortIdentifier actualPortId = (CommPortIdentifier)portEnum.nextElement();
    if(port.equals(actualPortId.getName())){
    portId = actualPortId;
    break;
    }
    }
    if(portId == null){
    showerror("There is no connection");
    
    }
    try{
    serialPort =(SerialPort)portId.open(this.getClass().getName(), timeOut);
    serialPort.setSerialPortParams(dataRate, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);
    output = serialPort.getOutputStream();
    
    
    }
    catch(PortInUseException | UnsupportedCommOperationException | IOException e){
    showerror(e.getMessage());  
    }}
     
      private void sendData(String data){
    try{
    output.write(data.getBytes());
    
    }
    catch(Exception e){
    showerror("error");
    System.exit(ERROR);
    }
    }
    public void showerror(String msg){
        JOptionPane.showMessageDialog(null,msg);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        living = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        roomA = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn1on = new javax.swing.JButton();
        btn1off = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btn1on1 = new javax.swing.JButton();
        btn1off1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btn1on2 = new javax.swing.JButton();
        btn1off2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        slid = new javax.swing.JSlider();
        door = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 62, 96));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(null);

        living.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room3off.png"))); // NOI18N
        jPanel2.add(living);
        living.setBounds(550, 180, 400, 250);
        jPanel2.add(jLabel4);
        jLabel4.setBounds(700, 290, 0, 0);

        roomA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/room1off.png"))); // NOI18N
        jPanel2.add(roomA);
        roomA.setBounds(630, 390, 200, 180);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house-plan.png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(440, 160, 550, 470);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(0, 0, 0, 2);

        jPanel5.setBackground(new java.awt.Color(31, 46, 127));
        jPanel5.setLayout(null);
        jPanel5.add(jSeparator1);
        jSeparator1.setBounds(0, 30, 577, 20);

        jPanel10.setBackground(new java.awt.Color(40, 53, 123));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Plug socket");

        btn1on.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlamp.png"))); // NOI18N
        btn1on.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1onActionPerformed(evt);
            }
        });

        btn1off.setIcon(new javax.swing.ImageIcon(getClass().getResource("/offlamp.png"))); // NOI18N
        btn1off.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1offActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(btn1on, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1off, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1off, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1on, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel10);
        jPanel10.setBounds(10, 40, 100, 110);

        jPanel11.setBackground(new java.awt.Color(40, 53, 123));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Living Room");

        btn1on1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlamp.png"))); // NOI18N
        btn1on1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1on1ActionPerformed(evt);
            }
        });

        btn1off1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/offlamp.png"))); // NOI18N
        btn1off1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1off1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn1on1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1off1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1off1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1on1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel11);
        jPanel11.setBounds(120, 40, 105, 110);

        jPanel13.setBackground(new java.awt.Color(40, 53, 123));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("All at once");

        btn1on2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/onlamp.png"))); // NOI18N
        btn1on2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1on2ActionPerformed(evt);
            }
        });

        btn1off2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/offlamp.png"))); // NOI18N
        btn1off2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1off2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn1on2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1off2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn1off2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn1on2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel13);
        jPanel13.setBounds(230, 40, 100, 110);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Home security");
        jPanel5.add(jLabel5);
        jLabel5.setBounds(10, 340, 168, 31);
        jPanel5.add(jSeparator5);
        jSeparator5.setBounds(0, 200, 577, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gate System");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(10, 150, 168, 20);
        jPanel5.add(jSeparator4);
        jSeparator4.setBounds(0, 374, 567, 20);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Light System");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(10, 0, 168, 31);

        jPanel7.setBackground(new java.awt.Color(40, 53, 123));
        jPanel7.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Security system!!!");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(10, 35, 220, 31);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/radioon.png"))); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton9);
        jButton9.setBounds(190, 20, 60, 60);

        jPanel5.add(jPanel7);
        jPanel7.setBounds(10, 390, 280, 110);

        slid.setBackground(new java.awt.Color(40, 53, 123));
        slid.setPaintLabels(true);
        slid.setPaintTicks(true);
        slid.setSnapToTicks(true);
        slid.setValue(0);
        slid.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slidStateChanged(evt);
            }
        });
        jPanel5.add(slid);
        slid.setBounds(10, 220, 200, 31);

        door.setIcon(new javax.swing.ImageIcon(getClass().getResource("/closedgate.png"))); // NOI18N
        jPanel5.add(door);
        door.setBounds(310, 200, 130, 170);

        jLabel6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel6MouseDragged(evt);
            }
        });
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel6MousePressed(evt);
            }
        });
        jPanel5.add(jLabel6);
        jLabel6.setBounds(0, -46, 940, 630);

        fan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fanstop.gif"))); // NOI18N
        jPanel5.add(fan);
        fan.setBounds(310, 370, 130, 160);

        jPanel2.add(jPanel5);
        jPanel5.setBounds(0, 0, 440, 590);

        display.setEditable(false);
        display.setBackground(new java.awt.Color(40, 53, 123));
        display.setBorder(null);
        jScrollPane1.setViewportView(display);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(450, 30, 200, 170);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/spining.gif"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(870, 0, 64, 60);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Light System");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(10, 0, 168, 31);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Light System");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(10, 0, 168, 31);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover2.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(364, -101, 580, 770);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 40, 940, 590);

        jPanel4.setBackground(new java.awt.Color(23, 37, 112));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinLog.png"))); // NOI18N
        jLabel16.setText("home control");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 440, 40);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(466, Short.MAX_VALUE)
                .addComponent(close)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addComponent(close, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(440, 0, 500, 40);

        setSize(new java.awt.Dimension(937, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int count=0;
    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       count=count+1;
        int mod = count%2;
        if(mod!=0){
        sendData(fan_on);
        fan.setIcon(new ImageIcon("src/fanturn.gif"));
        }
        else{
         sendData(fan_off);
        fan.setIcon(new ImageIcon("src/fanstop.gif"));
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void slidStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidStateChanged
         
        int val = slid.getValue();
        if(val==0){
        sendData(door_close);
        door.setIcon(new ImageIcon("src/closedgate.png"));   
        }
        if(val==100){
        sendData(door_open);
        door.setIcon(new ImageIcon("src/openGate.png"));   
        }
    }//GEN-LAST:event_slidStateChanged

    private void btn1onActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1onActionPerformed
        sendData(room3_on);
        roomA.setIcon(new ImageIcon("src/room1on.png"));
    }//GEN-LAST:event_btn1onActionPerformed

    private void btn1offActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1offActionPerformed
        sendData(room3_off);
        roomA.setIcon(new ImageIcon("src/room1off.png"));
    }//GEN-LAST:event_btn1offActionPerformed

    private void btn1on1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1on1ActionPerformed
        sendData(room1_on);
        living.setIcon(new ImageIcon("src/room3on.png"));
    }//GEN-LAST:event_btn1on1ActionPerformed

    private void btn1off1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1off1ActionPerformed
         sendData(room1_off);
        living.setIcon(new ImageIcon("src/room3off.png"));
    }//GEN-LAST:event_btn1off1ActionPerformed

    private void btn1on2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1on2ActionPerformed
         sendData(all_on);
         living.setIcon(new ImageIcon("src/room3on.png"));
         roomA.setIcon(new ImageIcon("src/room1on.png"));
         
    }//GEN-LAST:event_btn1on2ActionPerformed

    private void btn1off2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1off2ActionPerformed
         sendData(all_off);
         living.setIcon(new ImageIcon("src/room3off.png"));
         roomA.setIcon(new ImageIcon("src/room1off.png"));
        
       
    }//GEN-LAST:event_btn1off2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
    }//GEN-LAST:event_formWindowOpened
int count2 =0; 
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
           String input;
        if(count2 % 2 == 0){
            input=("http://192.168.4.1/");
        
              // input=this.address.getText();
        
        try {
            //this.display.setPage(input);
          display.setPage(input);
        } catch (IOException ex) {
            Logger.getLogger(HouseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        count2 = count2+1;
       }
        else if(count2 % 2 != 0){
               input=("http://192.168.4.1");
        
               //input=this.address.getText();
        
        try {
            //this.display.setPage(input);
            display.setPage(input);
        } catch (IOException ex) {
            Logger.getLogger(HouseForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         count2 = count2+1;
        }
    }//GEN-LAST:event_jPanel2MousePressed

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        setVisible(false);
        new Interface1().setVisible(true);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setSize(29,29);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setSize(32,32);
    }//GEN-LAST:event_closeMouseExited

    private void jLabel6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseDragged
        // TODO add your handling code here:
         int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_jLabel6MouseDragged

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MousePressed
         xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_jLabel6MousePressed
  int xMouse;
  int yMouse;              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HouseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new HouseForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1off;
    private javax.swing.JButton btn1off1;
    private javax.swing.JButton btn1off2;
    private javax.swing.JButton btn1on;
    private javax.swing.JButton btn1on1;
    private javax.swing.JButton btn1on2;
    private javax.swing.JLabel close;
    private javax.swing.JTextPane display;
    private javax.swing.JLabel door;
    private javax.swing.JLabel fan;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel living;
    private javax.swing.JLabel roomA;
    private javax.swing.JSlider slid;
    // End of variables declaration//GEN-END:variables
}
