
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.Timer;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pasxzy72
 */
public final class Interface1 extends javax.swing.JFrame {
    private Object datelab;

    /**
     * Creates new form Interface1
     */
    public Interface1() {
        initComponents();
        showDate();
        showTime();
    }
void showDate(){
Date d = new Date();
SimpleDateFormat s = new SimpleDateFormat("mm-dd-yyy");
//datelab.setText(s.format(d));
}
void showTime(){
       new Timer(0, (ActionEvent e) -> {
           Date d = new Date();
           SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss a");
           timelab.setText(s.format(d));
       }).start();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        msg1 = new javax.swing.JLabel();
        house = new javax.swing.JLabel();
        setting = new javax.swing.JLabel();
        server = new javax.swing.JLabel();
        help1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        timelab = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(2, 62, 96));
        setMinimumSize(new java.awt.Dimension(937, 625));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeMouseExited(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(660, 10, 24, 24);

        minimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/minimize-icon.png"))); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizeMouseExited(evt);
            }
        });
        jPanel1.add(minimize);
        minimize.setBounds(630, 10, 24, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(250, 0, 1100, 40);

        jPanel2.setBackground(new java.awt.Color(206, 219, 235));
        jPanel2.setLayout(null);

        msg1.setBackground(new java.awt.Color(255, 255, 255));
        msg1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        msg1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(msg1);
        msg1.setBounds(570, 290, 360, 40);

        house.setBackground(new java.awt.Color(29, 56, 123));
        house.setIcon(new javax.swing.ImageIcon(getClass().getResource("/house1.png"))); // NOI18N
        house.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                houseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                houseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                houseMouseExited(evt);
            }
        });
        jPanel2.add(house);
        house.setBounds(10, 40, 220, 230);

        setting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/setting1.png"))); // NOI18N
        setting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingMouseExited(evt);
            }
        });
        jPanel2.add(setting);
        setting.setBounds(240, 40, 220, 230);

        server.setIcon(new javax.swing.ImageIcon(getClass().getResource("/security1.png"))); // NOI18N
        server.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                serverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                serverMouseExited(evt);
            }
        });
        jPanel2.add(server);
        server.setBounds(460, 40, 220, 230);

        help1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/help1.png"))); // NOI18N
        help1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                help1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                help1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                help1MouseExited(evt);
            }
        });
        jPanel2.add(help1);
        help1.setBounds(10, 280, 230, 230);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(44, 62, 80));
        jLabel16.setText("Copyright© 2019 Idukunda lengo lionel");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(480, 560, 211, 30);
        jPanel2.add(jLabel3);
        jLabel3.setBounds(580, 350, 0, 0);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover2.png"))); // NOI18N
        jPanel2.add(jLabel12);
        jLabel12.setBounds(-10, -10, 1130, 610);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(250, 40, 690, 590);

        jPanel5.setBackground(new java.awt.Color(31, 46, 127));
        jPanel5.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shalogo.png"))); // NOI18N
        jPanel5.add(jLabel1);
        jLabel1.setBounds(20, 60, 208, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        jPanel5.add(jLabel2);
        jLabel2.setBounds(10, 315, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/House-icon.png"))); // NOI18N
        jPanel5.add(jLabel5);
        jLabel5.setBounds(49, 222, 32, 32);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome");
        jPanel5.add(jLabel6);
        jLabel6.setBounds(99, 222, 103, 32);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fast and Easy");
        jPanel5.add(jLabel8);
        jLabel8.setBounds(73, 11, 100, 32);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/clock-icon.png"))); // NOI18N
        jPanel5.add(jLabel10);
        jLabel10.setBounds(10, 423, 64, 32);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Mail-icon.png"))); // NOI18N
        jPanel5.add(jLabel11);
        jLabel11.setBounds(10, 373, 64, 32);

        logout.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Log Out");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        jPanel5.add(logout);
        logout.setBounds(60, 310, 95, 38);

        timelab.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 16)); // NOI18N
        timelab.setForeground(new java.awt.Color(255, 255, 255));
        timelab.setText("Time");
        jPanel5.add(timelab);
        timelab.setBounds(60, 420, 156, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ilelio@yahoo.fr");
        jPanel5.add(jLabel9);
        jLabel9.setBounds(60, 370, 116, 32);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cover.png"))); // NOI18N
        jPanel5.add(jLabel4);
        jLabel4.setBounds(0, 30, 250, 490);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 40, 250, 590);

        jPanel3.setBackground(new java.awt.Color(23, 37, 112));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinLog.png"))); // NOI18N
        jLabel7.setText("home");

        jLabel13.setText("jLabel13");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FinLog.png"))); // NOI18N
        jLabel14.setText("help");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 937, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(414, 414, 414)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addGap(414, 414, 414)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 553, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(252, 252, 252)
                    .addComponent(jLabel14)
                    .addContainerGap(253, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 250, 553);

        setSize(new java.awt.Dimension(940, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        System.exit(1);
    }//GEN-LAST:event_closeMouseClicked

    private void closeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseEntered
        close.setSize(29,29);
    }//GEN-LAST:event_closeMouseEntered

    private void closeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseExited
        close.setSize(32,32);
    }//GEN-LAST:event_closeMouseExited

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void minimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseEntered
        minimize.setSize(29,29);
    }//GEN-LAST:event_minimizeMouseEntered

    private void minimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseExited
        minimize.setSize(32,32);
    }//GEN-LAST:event_minimizeMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setText("Sign Out");
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
         logout.setText("Log Out");
    }//GEN-LAST:event_logoutMouseExited

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        setVisible(false);
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void serverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serverMouseEntered
         server.setIcon(new ImageIcon("src/security2.png"));
         
    }//GEN-LAST:event_serverMouseEntered

    private void serverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serverMouseExited
         server.setIcon(new ImageIcon("src/security1.png"));
    }//GEN-LAST:event_serverMouseExited

    private void serverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serverMouseClicked
        // TODO add your handling code here:
       // System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
       // new Camera().setVisible(true);
        String url ="http://localhost/surveillance/";
        
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
             
        } catch (IOException ex) {
            Logger.getLogger(Interface1.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_serverMouseClicked

    private void help1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help1MouseExited
        help1.setIcon(new ImageIcon("src/help1.png"));
    }//GEN-LAST:event_help1MouseExited

    private void help1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help1MouseEntered
        help1.setIcon(new ImageIcon("src/help2.png"));
    }//GEN-LAST:event_help1MouseEntered

    private void help1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_help1MouseClicked
    new HelpFrom().setVisible(true);
    setVisible (false);
    }//GEN-LAST:event_help1MouseClicked

    private void houseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseExited
        house.setIcon(new ImageIcon("src/house1.png"));
    }//GEN-LAST:event_houseMouseExited

    private void houseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseEntered
        house.setIcon(new ImageIcon("src/house2.png"));
    }//GEN-LAST:event_houseMouseEntered

    private void houseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_houseMouseClicked
       
        new HouseForm().setVisible(true);
    }//GEN-LAST:event_houseMouseClicked

    private void settingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseExited
        setting.setIcon(new ImageIcon("src/setting1.png"));
    }//GEN-LAST:event_settingMouseExited

    private void settingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseEntered
        setting.setIcon(new ImageIcon("src/settings2.png"));
    }//GEN-LAST:event_settingMouseEntered

    private void settingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingMouseClicked
        setVisible(false);
        new SettingForm().setVisible(true);
    }//GEN-LAST:event_settingMouseClicked
    int xMouse;
    int yMouse;
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interface1().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel help1;
    private javax.swing.JLabel house;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel msg1;
    private javax.swing.JLabel server;
    private javax.swing.JLabel setting;
    private javax.swing.JLabel timelab;
    // End of variables declaration//GEN-END:variables
}
